print('======================== DESAFIO 4 ===========================')
x: str=input('Conte-me um segredo ')
print( 'O que você escreveu é do tipo:',type(x))
print('Tem somente letras?', x.isalpha())
print('Tem somente números?', x.isnumeric())
print('Está só em minúsculas?',x.islower())
print('Está só em maiscúslas?', x.isupper())
print('É identificável?', x.isidentifier())
print('========================= FIM =================================')