print('======================== DESAFIO 13 ======================================')
print('AUMENTO DE 15% EM SEU SALÁRIO!!!')
a=float(input('Qual é o seu salário atual? '))
b = a + (a*3/20)
print(f'Aqui está o valor de seu salário depois do aumento: {b}')